[package]
name = "wizardwars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.17"
anyhow = "1"
winit = "0.28"
tokio = { version = "1", features = ["full"] }
bytemuck = { version = "1",  features = [ "derive" ] }
log = "0.4"
cgmath = "0.18"
simple_logger = "4"